name: mqtt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - autopep8==2.3.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.53.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - msgpack==1.0.8
      - numpy==2.1.1
      - opencv-python==4.10.0.84
      - packaging==24.1
      - paho-mqtt==1.5.1
      - pillow==10.4.0
      - pycodestyle==2.12.1
      - pymycobot==3.5.3
      - pyparsing==3.1.4
      - pyserial==3.5
      - python-can==4.4.2
      - python-dateutil==2.9.0.post0
      - six==1.16.0
      - typing-extensions==4.12.2
      - wrapt==1.16.0
prefix: /home/gursi26/miniconda3/envs/mqtt
